### ISSUE TITLE
추가 수정 정보

### ISSUE THREAD

**Issue by CHOUMnote** [neoman-omyeon-go/BigsasimiServer#15]
- [x] 나트륨 미수정 이슈
- [x] 프로필 이미지 변경
- [x] 리스트 처리시 중복 및 널값 처리하기

**Comment by CHOUMnote** [comment]
@LifeIsRightward 이거 확인좀

**Comment by LifeIsRightward** [comment]
+ 영양정보 API 부분에 당류 추가하기

**Comment by LifeIsRightward** [comment]
영양정보 모든 API에 대해 당류가 추가되어야 해 ㅇㅋ?

**Comment by LifeIsRightward** [comment]
1,2 문제해결 확인

**Comment by CHOUMnote** [comment]
@LifeIsRightward 배포했으니 패치 받으세요
내가 어느정도 테스트는 했는데 실질적으로 프론트에서도 해봐야 합니다~

**Comment by LifeIsRightward** [comment]
확인이요~
