### ISSUE TITLE
배포관련 문제를 다룹니다.

### ISSUE THREAD

**Issue by CHOUMnote** [neoman-omyeon-go/BigsasimiServer#2]
확인사항 
1. settings 파일의 `DATABASES`값을 `DATABASES_SELECT['postgres']`로 변경
2. 도커 파일 runserver 안하도록 주석처리
3. `docker compose up -d`
4. 테스트

이렇게 해서 안되면 망한거 ㅠㅠ 

- [x]  로컬테스트
- [x] vm환경 테스트
- [x] 배포환경 테스트

**Comment by LifeIsRightward** [comment]
저번에 이미 docker 환경세팅을 맥북에 해놨는데, 처음부터 다시 clone하고 받아야하나요?

**Comment by CHOUMnote** [comment]
@LifeIsRightward 기존 있던거 밀어버리고 다시 클론을 받거나 pull받아서 위 명령어 하면 됨

**Comment by CHOUMnote** [comment]
오늘자로 배포 문제 없음을 확인

문제있다면 맨션 부탁드립니다.
