### ISSUE TITLE
사진 업로드 기능 및 관련 이모저모

### ISSUE THREAD

**Issue by CHOUMnote** [neoman-omyeon-go/BigsasimiServer#5]
### 사진 촬영 관련 기능

**개발 사항 목록...**

- [x] #6
- [x] #8 
- [x] ai서버 넘기기
- [x] ai서버로부터 결과 받기
- [x] 데이터 정렬 및 저장
- [x] 관련 API 추가

> 추가사항은 코멘트로

**Comment by CHOUMnote** [comment]
@LifeIsRightward 지금 생각나는 선에서 다 만들어 놓음 확인해보고 필요한거나 안되는거 있으면 말하셈 ㅇㅇ

**Comment by LifeIsRightward** [comment]
요즘 중간고사라 정신이 없습니다... 얼른얼른 해볼게요
