### ISSUE TITLE
영양정보 DB 스키마 설계

### ISSUE THREAD

**Issue by CHOUMnote** [neoman-omyeon-go/BigsasimiServer#8]
### DB 관련

프로필 : 개인정보 + 질환정보 + 섭취중인 약이나 영양제 등등
섭취 로그 : 타임라인 형식으로 뭐 먹었는지 기록 및 해당 데이터를 이용한 기능 설계
영양성분 : 여러가지 영양성분 기준 정하고 테이블 구성 

- [x] #9
- [x] 섭취로그 작성
- [x] 영양성분 작성

**Comment by CHOUMnote** [comment]
@LifeIsRightward 프로필 정보 관련 업데이트 함 #9 
포스트맨 보십셔

**Comment by LifeIsRightward** [comment]
확인했습니다!
